version: "3"
services:

  version_1:
    image: msfidelis/micro-api:v1
    networks:
      - developer

  version_2:
    image: msfidelis/micro-api:v2
    networks:
      - developer

  envoy_proxy:
    build: .
    ports:
      - "8080:8080"
    networks:
      - developer

networks:
  developer: