version: "3"
services:

  service_example:
    image: fidelissauro/chip:v1
    ports:
      - "9090:8080"
    networks:
      - developer

  envoy_proxy:
    build: .
    ports:
      - "8080:8080"
    networks:
      - developer

networks:
  developer:
