version: "3"
services:


  service_whois:
    image: msfidelis/whois:v1
    ports:
      - "9090:8080"
    networks:
      - developer

  service_faker:
    image: msfidelis/faker:v1
    ports:
      - "5000:5000"
    networks:
      - developer

  envoy_proxy:
    build: .
    ports:
      - "8080:8080"
    networks:
      - developer

networks:
  developer: